framework:
    uid:
        default_uuid_version: 1
        name_based_uuid_version: 5
        name_based_uuid_namespace: 6ba7b810-9dad-11d1-80b4-00c04fd430c8
        time_based_uuid_version: 1
        time_based_uuid_node: fb3502dc-137e-4849-8886-ac90d07f64a7