<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */

return [
    'app' => [
        'path' => './assets/app.js',
        'entrypoint' => true,
    ],
    '@symfony/stimulus-bundle' => [
        'path' => './vendor/symfony/stimulus-bundle/assets/dist/loader.js',
    ],
    '@hotwired/stimulus' => [
        'version' => '3.2.2',
    ],
    'flowbite/plugin' => [
        'version' => '2.2.0',
    ],
    'mini-svg-data-uri' => [
        'version' => '1.4.4',
    ],
    'tailwindcss/plugin' => [
        'version' => '3.3.6',
    ],
    'tailwindcss/defaultTheme' => [
        'version' => '3.3.6',
    ],
    'tailwindcss/colors' => [
        'version' => '3.3.6',
    ],
    'picocolors' => [
        'version' => '1.0.0',
    ],
    'flowbite' => [
        'version' => '2.2.0',
    ],
    '@popperjs/core' => [
        'version' => '2.11.8',
    ],
    'flowbite/dist/flowbite.min.css' => [
        'version' => '2.2.0',
        'type' => 'css',
    ],
    'hls.js' => [
        'version' => '1.4.13',
    ],
    '@hotwired/turbo' => [
        'version' => '7.3.0',
    ],
    'filepond' => [
        'version' => '4.30.4',
    ],
    'filepond/dist/filepond.min.css' => [
        'version' => '4.30.4',
        'type' => 'css',
    ],
    'tom-select' => [
        'version' => '2.3.1',
    ],
    'prettier-plugin-tailwindcss' => [
        'version' => '0.5.9',
    ],
    'tailwind-scrollbar' => [
        'version' => '3.0.5',
    ],
    'tailwindcss/lib/util/flattenColorPalette' => [
        'version' => '3.3.6',
    ],
    'tailwindcss/lib/util/toColorValue' => [
        'version' => '3.3.6',
    ],
    'tailwindcss/lib/featureFlags' => [
        'version' => '3.3.6',
    ],
    'mediaplayer' => [
        'version' => '2.0.1',
    ],
    'mediaplayer/index.min.css' => [
        'version' => '2.0.1',
        'type' => 'css',
    ],
];
