<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'app' => [
        'path' => './assets/app.js',
        'entrypoint' => true,
    ],
    '@symfony/stimulus-bundle' => [
        'path' => './vendor/symfony/stimulus-bundle/assets/dist/loader.js',
    ],
    '@hotwired/stimulus' => [
        'version' => '3.2.2',
    ],
    'flowbite/plugin' => [
        'version' => '2.2.1',
    ],
    'mini-svg-data-uri' => [
        'version' => '1.4.4',
    ],
    'tailwindcss/plugin' => [
        'version' => '3.4.0',
    ],
    'tailwindcss/defaultTheme' => [
        'version' => '3.3.5',
    ],
    'tailwindcss/colors' => [
        'version' => '3.3.5',
    ],
    'picocolors' => [
        'version' => '1.0.0',
    ],
    'flowbite' => [
        'version' => '2.2.1',
    ],
    'flowbite/dist/flowbite.min.css' => [
        'version' => '2.2.1',
        'type' => 'css',
    ],
    'hls.js' => [
        'version' => '1.4.14',
    ],
    '@hotwired/turbo' => [
        'version' => '7.3.0',
    ],
    'filepond' => [
        'version' => '4.30.6',
    ],
    'filepond/dist/filepond.min.css' => [
        'version' => '4.30.6',
        'type' => 'css',
    ],
    'tom-select' => [
        'version' => '2.3.1',
    ],
    'prettier-plugin-tailwindcss' => [
        'version' => '0.5.10',
    ],
    'tailwind-scrollbar' => [
        'version' => '3.0.5',
    ],
    'tailwindcss/lib/util/flattenColorPalette' => [
        'version' => '3.4.0',
    ],
    'tailwindcss/lib/util/toColorValue' => [
        'version' => '3.4.0',
    ],
    'tailwindcss/lib/featureFlags' => [
        'version' => '3.4.0',
    ],
    'mediaplayer' => [
        'version' => '2.0.1',
    ],
    'mediaplayer/index.min.css' => [
        'version' => '2.0.1',
        'type' => 'css',
    ],
    'debounce' => [
        'version' => '2.0.0',
    ],
    'turbo-view-transitions' => [
        'version' => '0.3.0',
    ],
    'stimulus-use' => [
        'version' => '0.52.2',
    ],
    'stimulus-popover' => [
        'version' => '6.2.0',
    ],
    'tom-select/dist/css/tom-select.default.css' => [
        'version' => '2.3.1',
        'type' => 'css',
    ],
    '@popperjs/core' => [
        'version' => '2.11.8',
    ],
    '@tailwindcss/container-queries' => [
        'version' => '0.1.1',
    ],
    '@tailwindcss/forms' => [
        'version' => '0.5.7',
    ],
    '@tailwindcss/aspect-ratio' => [
        'version' => '0.4.2',
    ],
    'pdf.js' => [
        'version' => '0.1.0',
    ],
    'jsdelivr' => [
        'version' => '0.1.2',
    ],
    'jquery' => [
        'version' => '3.7.1',
    ],
    'stimulus-checkbox-select-all' => [
        'version' => '5.3.0',
    ],
];
