controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix:
        de: '' # don't prefix URLs for English, the default locale
        en: '/en'
        fr: '/fr'

    kernel:
        resource: ../src/Kernel.php
        type: attribute
